name = "wildandwarp"
author = "dohc-dev"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27f4df6cd7e079cc86f07fce75bfa279cd52fe03ed0a9fce02b647fd20cd5da1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
