name = "citratus"
author = "dohc-dev"
version = "1.12.1-v0.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f357a3c60895dc77825e6106882bfee241139c9db5516c04ab7571174c5bc718"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
