name = "citratus"
author = "dohc-dev"
version = "1.12.1-v0.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc0709a29fd221ad37f15d5bc31c6346c0c9142aaae4b32dad386d6202a00d7a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
