name = "wildandwarp"
author = "dohc-dev"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "504bb5c79a5e30cf6b29099638af608438bad28c3f025d63cfdc5c9c670a4f22"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
