name = "wildandwarp"
author = "dohc-dev"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "696b53de3eba0975c89a1ab99b130cde59c5e3f18b61ded0f110b8dda532f3bd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
