name = "wildandwarp"
author = "dohc-dev"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5d28d7a7dc9ac32cf756e3ec327ba3db8697e26054d1d08740fa42cc5e6191a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
